services:
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Radio_Toolkit-symfony
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DATABASE_URL: "pgsql://symfony:symfony@db:5432/symfony"

  db:
    image: postgres:14
    container_name: Radio_Toolkit-database
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: